export const SEEDED_INTELLIGENCE_UPDATED_AT = "2026-03-26T12:00:00.000Z";

export const SEEDED_MAIZE_SNAPSHOT = {
  productKey: "maize",
  productName: "Maize",
  category: "produce",
  unit: "90kg bag",
  submissionsCount: 10,
  approvedMarkets: 10,
  lastUpdated: SEEDED_INTELLIGENCE_UPDATED_AT,
  overallAverage: 3120,
  overallTrendDirection: "stable",
  overallTrendPercentage: 2.1,
  bestMarket: {
    marketKey: "maize-nakuru-yellow-maize-desk-nakuru",
    marketName: "Nakuru Yellow Maize Desk",
    county: "Nakuru",
    avgPrice: 3800,
    minPrice: 3800,
    maxPrice: 3800,
    submissionsCount: 1,
    currentWindowCount: 1,
    lastUpdated: SEEDED_INTELLIGENCE_UPDATED_AT,
    trendDirection: "up",
    trendPercentage: 5.4,
    notes: "Higher yellow-maize signal separated from white-maize and farm-gate quotes.",
    sourceType: "external",
    sourceLabel: "Agrisoko maize baseline March 2026",
  },
  weakestMarket: {
    marketKey: "maize-njoro-grain-desk-nakuru",
    marketName: "Njoro Grain Desk",
    county: "Nakuru",
    avgPrice: 2500,
    minPrice: 2500,
    maxPrice: 2500,
    submissionsCount: 1,
    currentWindowCount: 1,
    lastUpdated: SEEDED_INTELLIGENCE_UPDATED_AT,
    trendDirection: "down",
    trendPercentage: -6.7,
    notes: "Lower Njoro-area quote represented as a county grain desk entry.",
    sourceType: "external",
    sourceLabel: "Agrisoko maize baseline March 2026",
  },
  markets: [
    {
      marketKey: "maize-nakuru-yellow-maize-desk-nakuru",
      marketName: "Nakuru Yellow Maize Desk",
      county: "Nakuru",
      avgPrice: 3800,
      minPrice: 3800,
      maxPrice: 3800,
      submissionsCount: 1,
      currentWindowCount: 1,
      lastUpdated: SEEDED_INTELLIGENCE_UPDATED_AT,
      trendDirection: "up",
      trendPercentage: 5.4,
      notes: "Higher yellow-maize signal separated from white-maize and farm-gate quotes.",
      sourceType: "external",
      sourceLabel: "Agrisoko maize baseline March 2026",
    },
    {
      marketKey: "maize-nakuru-premium-grain-desk-nakuru",
      marketName: "Nakuru Premium Grain Desk",
      county: "Nakuru",
      avgPrice: 3800,
      minPrice: 3800,
      maxPrice: 3800,
      submissionsCount: 1,
      currentWindowCount: 1,
      lastUpdated: SEEDED_INTELLIGENCE_UPDATED_AT,
      trendDirection: "up",
      trendPercentage: 5.1,
      notes: "Premium maize quote normalized without naming a specific farm or trader.",
      sourceType: "external",
      sourceLabel: "Agrisoko maize baseline March 2026",
    },
    {
      marketKey: "maize-national-wholesale-desk-kenya",
      marketName: "National Wholesale Desk",
      county: "Kenya",
      avgPrice: 3500,
      minPrice: 3500,
      maxPrice: 3500,
      submissionsCount: 1,
      currentWindowCount: 1,
      lastUpdated: SEEDED_INTELLIGENCE_UPDATED_AT,
      trendDirection: "up",
      trendPercentage: 3.8,
      notes: "Location-unspecified wholesale reference quote retained as a national comparison point.",
      sourceType: "external",
      sourceLabel: "Agrisoko maize baseline March 2026",
    },
    {
      marketKey: "maize-nakuru-wholesale-desk-nakuru",
      marketName: "Nakuru Wholesale Desk",
      county: "Nakuru",
      avgPrice: 3150,
      minPrice: 3150,
      maxPrice: 3150,
      submissionsCount: 1,
      currentWindowCount: 1,
      lastUpdated: SEEDED_INTELLIGENCE_UPDATED_AT,
      trendDirection: "stable",
      trendPercentage: 1.4,
      notes: "Wholesale white-maize signal.",
      sourceType: "external",
      sourceLabel: "Agrisoko maize baseline March 2026",
    },
    {
      marketKey: "maize-bungoma-grain-desk-bungoma",
      marketName: "Bungoma Grain Desk",
      county: "Bungoma",
      avgPrice: 3000,
      minPrice: 3000,
      maxPrice: 3000,
      submissionsCount: 1,
      currentWindowCount: 1,
      lastUpdated: SEEDED_INTELLIGENCE_UPDATED_AT,
      trendDirection: "stable",
      trendPercentage: 0.8,
      notes: "General regional dry-maize signal normalized into a county market desk entry.",
      sourceType: "external",
      sourceLabel: "Agrisoko maize baseline March 2026",
    },
    {
      marketKey: "maize-nakuru-farm-gate-desk-nakuru",
      marketName: "Nakuru Farm-Gate Desk",
      county: "Nakuru",
      avgPrice: 3000,
      minPrice: 3000,
      maxPrice: 3000,
      submissionsCount: 1,
      currentWindowCount: 1,
      lastUpdated: SEEDED_INTELLIGENCE_UPDATED_AT,
      trendDirection: "stable",
      trendPercentage: 0.6,
      notes: "County-level farm-gate style quote retained without naming a specific farm.",
      sourceType: "external",
      sourceLabel: "Agrisoko maize baseline March 2026",
    },
    {
      marketKey: "maize-migori-bulk-grain-desk-migori",
      marketName: "Migori Bulk Grain Desk",
      county: "Migori",
      avgPrice: 2950,
      minPrice: 2900,
      maxPrice: 3000,
      submissionsCount: 1,
      currentWindowCount: 1,
      lastUpdated: SEEDED_INTELLIGENCE_UPDATED_AT,
      trendDirection: "stable",
      trendPercentage: 0.3,
      notes: "Bulk quote reported as a range of KES 2,900 to 3,000; midpoint stored for analysis.",
      sourceType: "external",
      sourceLabel: "Agrisoko maize baseline March 2026",
    },
    {
      marketKey: "maize-north-rift-grain-desk-trans-nzoia",
      marketName: "North Rift Grain Desk",
      county: "Trans Nzoia",
      avgPrice: 2800,
      minPrice: 2800,
      maxPrice: 2800,
      submissionsCount: 1,
      currentWindowCount: 1,
      lastUpdated: SEEDED_INTELLIGENCE_UPDATED_AT,
      trendDirection: "down",
      trendPercentage: -2.4,
      notes: "Kitale-area maize signal normalized to a broader North Rift market desk.",
      sourceType: "external",
      sourceLabel: "Agrisoko maize baseline March 2026",
    },
    {
      marketKey: "maize-nakuru-grain-desk-nakuru",
      marketName: "Nakuru Grain Desk",
      county: "Nakuru",
      avgPrice: 2700,
      minPrice: 2700,
      maxPrice: 2700,
      submissionsCount: 1,
      currentWindowCount: 1,
      lastUpdated: SEEDED_INTELLIGENCE_UPDATED_AT,
      trendDirection: "down",
      trendPercentage: -4.1,
      notes: "Low-end clean dry-maize signal reported in Nakuru county.",
      sourceType: "external",
      sourceLabel: "Agrisoko maize baseline March 2026",
    },
    {
      marketKey: "maize-njoro-grain-desk-nakuru",
      marketName: "Njoro Grain Desk",
      county: "Nakuru",
      avgPrice: 2500,
      minPrice: 2500,
      maxPrice: 2500,
      submissionsCount: 1,
      currentWindowCount: 1,
      lastUpdated: SEEDED_INTELLIGENCE_UPDATED_AT,
      trendDirection: "down",
      trendPercentage: -6.7,
      notes: "Lower Njoro-area quote represented as a county grain desk entry.",
      sourceType: "external",
      sourceLabel: "Agrisoko maize baseline March 2026",
    },
  ],
  insight:
    "Starter maize signals already show why market intelligence matters. Current county quotes range from about KES 2,500 in lower Nakuru signals to KES 3,800 in stronger Nakuru premium and yellow-maize desks, with Bungoma, Migori, and Trans Nzoia sitting in between.",
  isFallback: true,
} as const;

export const SEEDED_MAIZE_RECENT_CONTRIBUTIONS = [
  {
    id: "seed-maize-nakuru-yellow-1",
    productKey: "maize",
    productName: "Maize",
    county: "Nakuru",
    marketName: "Nakuru Yellow Maize Desk",
    price: 3800,
    unit: "90kg bag",
    sourceType: "external",
    contributorName: "Agrisoko market desk",
    observationDate: SEEDED_INTELLIGENCE_UPDATED_AT,
  },
  {
    id: "seed-maize-bungoma-1",
    productKey: "maize",
    productName: "Maize",
    county: "Bungoma",
    marketName: "Bungoma Grain Desk",
    price: 3000,
    unit: "90kg bag",
    sourceType: "external",
    contributorName: "Agrisoko market desk",
    observationDate: SEEDED_INTELLIGENCE_UPDATED_AT,
  },
  {
    id: "seed-maize-trans-nzoia-1",
    productKey: "maize",
    productName: "Maize",
    county: "Trans Nzoia",
    marketName: "North Rift Grain Desk",
    price: 2800,
    unit: "90kg bag",
    sourceType: "external",
    contributorName: "Agrisoko market desk",
    observationDate: SEEDED_INTELLIGENCE_UPDATED_AT,
  },
  {
    id: "seed-maize-migori-1",
    productKey: "maize",
    productName: "Maize",
    county: "Migori",
    marketName: "Migori Bulk Grain Desk",
    price: 2950,
    unit: "90kg bag",
    sourceType: "external",
    contributorName: "Agrisoko market desk",
    observationDate: SEEDED_INTELLIGENCE_UPDATED_AT,
  },
] as const;

export const SEEDED_MAIZE_SEED_PRICE_SIGNAL = {
  publishedAt: "2026-03-25T11:00:00.000Z",
  revisedSubsidizedPrices: [
    { packSize: "1kg", price: 260 },
    { packSize: "2kg", price: 525 },
    { packSize: "10kg", price: 2625 },
    { packSize: "25kg", price: 6560 },
  ],
  reportedPreviousPrices: [
    { packSize: "1kg", price: 300 },
    { packSize: "2kg", price: 600 },
    { packSize: "10kg", price: 3000 },
    { packSize: "25kg", price: 7500 },
  ],
  conflictingRetainedPricesStillCirculating: [
    { packSize: "1kg", price: 210 },
    { packSize: "2kg", price: 420 },
    { packSize: "10kg", price: 2100 },
    { packSize: "25kg", price: 5250 },
  ],
  note:
    "Multiple March 25-26, 2026 posts repeated the revised subsidized schedule, but older retained-price graphics were also still being reshared. Farmers should confirm the actual depot or stockist price before purchase.",
} as const;
